#include "Engine.hpp"
#include "ASTBuilder.hpp"
#include "ApproximateFontMetrics.hpp"
#include "LayoutEngine.hpp"
#include "Lexer.hpp"
#include "MathParser.hpp"
#include "MathLayoutEngine.hpp"
#include "PageGeometry.hpp"

#include <algorithm>
#include <cctype>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

namespace mdcore {

namespace {

std::string trim(const std::string& text) {
    auto begin = std::find_if_not(text.begin(), text.end(), [](unsigned char ch) {
        return std::isspace(ch);
    });
    auto end = std::find_if_not(text.rbegin(), text.rend(), [](unsigned char ch) {
        return std::isspace(ch);
    }).base();

    if (begin >= end) {
        return "";
    }
    return std::string(begin, end);
}

bool startsWith(const std::string& text, const std::string& prefix) {
    return text.rfind(prefix, 0) == 0;
}

bool contains(const std::string& text, const std::string& needle) {
    return text.find(needle) != std::string::npos;
}

void replaceAll(std::string& text, const std::string& needle, const std::string& replacement) {
    std::size_t position = 0;
    while ((position = text.find(needle, position)) != std::string::npos) {
        text.replace(position, needle.size(), replacement);
        position += replacement.size();
    }
}

std::string normalizeLigatures(std::string text) {
    replaceAll(text, "\xEF\xAC\x80", "ff");
    replaceAll(text, "\xEF\xAC\x81", "fi");
    replaceAll(text, "\xEF\xAC\x82", "fl");
    replaceAll(text, "\xEF\xAC\x83", "ffi");
    replaceAll(text, "\xEF\xAC\x84", "ffl");
    return text;
}

std::vector<std::string> splitLines(std::string text) {
    std::replace(text.begin(), text.end(), '\f', '\n');

    std::vector<std::string> lines;
    std::istringstream stream(text);
    std::string line;
    while (std::getline(stream, line)) {
        if (!line.empty() && line.back() == '\r') {
            line.pop_back();
        }
        lines.push_back(line);
    }
    return lines;
}

bool isDateTimePrintHeader(const std::string& line) {
    // Browser print headers generated by MarkItDown often look like "6/2/26, 1:35".
    auto comma = line.find(',');
    if (comma == std::string::npos) {
        return false;
    }

    std::string date = trim(line.substr(0, comma));
    std::string time = trim(line.substr(comma + 1));
    if (date.empty() || time.size() < 4 || time.size() > 5) {
        return false;
    }

    int slashCount = 0;
    for (unsigned char ch : date) {
        if (ch == '/') {
            slashCount += 1;
        } else if (!std::isdigit(ch)) {
            return false;
        }
    }
    if (slashCount != 2) {
        return false;
    }

    auto colon = time.find(':');
    if (colon == std::string::npos || colon == 0 || colon + 1 >= time.size()) {
        return false;
    }
    return std::all_of(time.begin(), time.end(), [](unsigned char ch) {
        return std::isdigit(ch) || ch == ':';
    });
}

bool isPageCounter(const std::string& line) {
    auto slash = line.find('/');
    if (slash == std::string::npos || slash == 0 || slash + 1 >= line.size()) {
        return false;
    }
    return std::all_of(line.begin(), line.end(), [](unsigned char ch) {
        return std::isdigit(ch) || ch == '/';
    });
}

bool isFileImageReference(const std::string& line) {
    auto normalized = normalizeLigatures(line);
    if (!startsWith(normalized, "(/")) {
        return false;
    }
    return contains(normalized, ".png)") || contains(normalized, ".jpg)") ||
           contains(normalized, ".jpeg)") || contains(normalized, ".gif)") ||
           contains(normalized, ".webp)");
}

bool isLikelyOcrGarbage(const std::string& line) {
    if (line.empty()) {
        return false;
    }
    if (contains(line, "\xEF\xBF\xBD")) {
        return true;
    }

    int asciiLetters = 0;
    int digits = 0;
    int symbols = 0;
    for (unsigned char ch : line) {
        if (std::isalpha(ch)) {
            asciiLetters += 1;
        } else if (std::isdigit(ch)) {
            digits += 1;
        } else if (!std::isspace(ch) && ch < 128) {
            symbols += 1;
        }
    }

    return line.size() >= 8 && asciiLetters <= 2 && digits <= 2 && symbols >= 5;
}

bool isPipeRow(const std::string& line) {
    std::string t = trim(line);
    return t.size() >= 3 && t.front() == '|' && t.find('|', 1) != std::string::npos;
}

std::vector<std::string> splitPipeCells(const std::string& line) {
    std::string t = trim(line);
    if (!t.empty() && t.front() == '|') {
        t.erase(t.begin());
    }
    if (!t.empty() && t.back() == '|') {
        t.pop_back();
    }

    std::vector<std::string> cells;
    std::string cell;
    std::istringstream stream(t);
    while (std::getline(stream, cell, '|')) {
        cells.push_back(trim(cell));
    }
    return cells;
}

bool isSeparatorRow(const std::vector<std::string>& cells) {
    if (cells.empty()) {
        return false;
    }

    int separatorCells = 0;
    for (const auto& cell : cells) {
        if (cell.empty()) {
            separatorCells += 1;
            continue;
        }

        bool valid = std::all_of(cell.begin(), cell.end(), [](unsigned char ch) {
            return ch == '-' || ch == ':' || std::isspace(ch);
        });
        if (!valid || cell.find('-') == std::string::npos) {
            return false;
        }
        separatorCells += 1;
    }
    return separatorCells > 0;
}

std::string joinNonEmptyCells(const std::vector<std::string>& cells) {
    std::string joined;
    for (const auto& cell : cells) {
        if (cell.empty()) {
            continue;
        }
        if (!joined.empty()) {
            joined += " ";
        }
        joined += cell;
    }
    return joined;
}

bool looksLikeMarkItDownLayoutTable(const std::vector<std::string>& rows) {
    int maxColumns = 0;
    int totalCells = 0;
    int emptyCells = 0;
    int nonSeparatorRows = 0;
    int shortCells = 0;
    int nonEmptyCells = 0;
    int nonSeparatorCells = 0;

    for (const auto& row : rows) {
        auto cells = splitPipeCells(row);
        maxColumns = std::max(maxColumns, static_cast<int>(cells.size()));
        if (isSeparatorRow(cells)) {
            continue;
        }

        nonSeparatorRows += 1;
        totalCells += static_cast<int>(cells.size());
        for (const auto& cell : cells) {
            nonSeparatorCells += 1;
            if (cell.empty()) {
                emptyCells += 1;
            } else {
                nonEmptyCells += 1;
                if (cell.size() <= 18) {
                    shortCells += 1;
                }
            }
        }
    }

    if (nonSeparatorRows == 0 || totalCells == 0) {
        return false;
    }

    double emptyRatio = static_cast<double>(emptyCells) / static_cast<double>(totalCells);
    double shortRatio = nonEmptyCells == 0 ? 0.0 : static_cast<double>(shortCells) / static_cast<double>(nonEmptyCells);

    // Real Markdown tables are kept. These rules target OCR/layout tables: many columns,
    // sparse cells, and sentence fragments split across columns.
    return (maxColumns >= 8 && shortRatio >= 0.70) ||
           (maxColumns >= 5 && emptyRatio >= 0.25 && shortRatio >= 0.60) ||
           (maxColumns >= 4 && nonSeparatorRows == 1 && shortRatio >= 0.75) ||
           (maxColumns >= 6 && nonSeparatorRows <= 2 &&
            static_cast<double>(emptyCells) / static_cast<double>(nonSeparatorCells) >= 0.45);
}

bool isLikelyRecoveredHeading(const std::string& line) {
    std::string t = trim(line);
    if (t.size() < 3 || t.size() > 90 || startsWith(t, "#") || isPipeRow(t) ||
        contains(t, "://") || contains(t, "...")) {
        return false;
    }

    int letters = 0;
    int lowercase = 0;
    int uppercase = 0;
    int digits = 0;
    int symbols = 0;
    for (unsigned char ch : t) {
        if (std::isalpha(ch)) {
            letters += 1;
            if (std::islower(ch)) {
                lowercase += 1;
            } else if (std::isupper(ch)) {
                uppercase += 1;
            }
        } else if (std::isdigit(ch)) {
            digits += 1;
        } else if (!std::isspace(ch) && ch < 128) {
            symbols += 1;
        }
    }

    if (letters < 4 || lowercase > 0) {
        return false;
    }

    bool numberedSection = std::isdigit(static_cast<unsigned char>(t.front())) &&
                           t.find('.') != std::string::npos && uppercase >= 4 &&
                           digits <= 3 && symbols <= 4;
    bool compactUppercaseHeading = uppercase >= 4 && t.size() >= 12 && t.size() <= 60 &&
                                   digits <= 2 && symbols <= 2;
    return numberedSection || compactUppercaseHeading;
}

std::string preprocessMarkdown(const std::string& markdown) {
    auto lines = splitLines(markdown);
    std::unordered_map<std::string, int> frequencies;
    int printHeaderCount = 0;
    for (const auto& line : lines) {
        std::string t = trim(line);
        if (isDateTimePrintHeader(t)) {
            printHeaderCount += 1;
        }
        if (!t.empty()) {
            frequencies[t] += 1;
        }
    }
    bool browserPrintExport = printHeaderCount >= 3;

    std::vector<std::string> filtered;
    filtered.reserve(lines.size());
    for (const auto& line : lines) {
        std::string t = trim(line);
        if (browserPrintExport && t.empty()) {
            continue;
        }
        if (isDateTimePrintHeader(t) || isPageCounter(t) || isFileImageReference(t) ||
            (!isPipeRow(t) && isLikelyOcrGarbage(t))) {
            continue;
        }
        if (frequencies[t] >= 3 && (startsWith(t, "http://") || startsWith(t, "https://") ||
                                    contains(t, "Noticias, fotos, videos"))) {
            continue;
        }
        filtered.push_back(line);
    }

    std::vector<std::string> output;
    bool recoveredLayoutTables = false;
    for (std::size_t index = 0; index < filtered.size();) {
        if (!isPipeRow(filtered[index])) {
            output.push_back(filtered[index]);
            index += 1;
            continue;
        }

        std::vector<std::string> tableRows;
        std::size_t end = index;
        while (end < filtered.size() && isPipeRow(filtered[end])) {
            tableRows.push_back(filtered[end]);
            end += 1;
        }

        if (!looksLikeMarkItDownLayoutTable(tableRows)) {
            output.insert(output.end(), tableRows.begin(), tableRows.end());
            index = end;
            continue;
        }

        recoveredLayoutTables = true;
        for (const auto& row : tableRows) {
            auto cells = splitPipeCells(row);
            if (isSeparatorRow(cells)) {
                continue;
            }
            auto joined = joinNonEmptyCells(cells);
            if (!joined.empty()) {
                output.push_back(joined);
            }
        }
        index = end;
    }

    if (browserPrintExport || recoveredLayoutTables) {
        for (auto& line : output) {
            std::string t = trim(line);
            if (isLikelyRecoveredHeading(t)) {
                line = "## " + t;
            }
        }
    }

    std::string result;
    for (const auto& line : output) {
        result += line;
        result += '\n';
    }
    return result;
}

} // namespace

Engine::Engine(const std::string& language) : hyphenator_(language) {}

std::string Engine::engineVersion() const {
    return "MarkdownPrintCore 0.1.0 (C++17, interop nativo)";
}

std::vector<Token> Engine::tokenize(const std::string& markdown) const {
    Lexer lexer;
    return lexer.tokenize(preprocessMarkdown(markdown));
}

std::vector<Block> Engine::parse(const std::string& markdown) const {
    ASTBuilder builder;
    auto preprocessed = preprocessMarkdown(markdown);
    auto refs = Lexer::parseReferences(preprocessed);
    Lexer lexer;
    return builder.build(lexer.tokenize(preprocessed), refs);
}

Layout Engine::layout(const std::string& markdown, double pageWidth, double pageHeight) const {
    auto blocks = parse(markdown);
    PageGeometry geometry = PageGeometry::standardMargins(pageWidth, pageHeight);
    ApproximateFontMetrics metrics;
    Typography typo;
    typo.textJustified = justifyText_;
    LayoutEngine engine(geometry, metrics, typo, &hyphenator_);
    return engine.layout(blocks);
}

MathLayoutInfo Engine::layoutMath(const std::string& latex, bool displayStyle, double fontSize) const {
    MathLayoutInfo result;
    auto ast = math::parseMath(latex, displayStyle);
    if (!ast) return result;

    math::MathLayoutEngine layoutEngine;
    auto layout = layoutEngine.layout(ast, fontSize, displayStyle);

    result.glyphs.reserve(layout.boxes.size());
    for (const auto& box : layout.boxes) {
        MathGlyphInfo info;
        info.x = box.x;
        info.y = box.y;
        info.width = box.width;
        info.height = box.height;
        info.depth = box.depth;
        info.fontSize = box.fontSize;
        info.isRule = box.isRule;
        info.isRadical = box.isRadical;
        info.unicode = box.unicode.empty() ? box.text : box.unicode;
        info.text = box.text;
        info.radicalContentHeight = box.radicalContentHeight;
        info.radicalContentWidth = box.radicalContentWidth;
        result.glyphs.push_back(std::move(info));
    }

    result.totalWidth = layout.totalWidth;
    result.totalHeight = layout.totalHeight;
    result.totalDepth = layout.totalDepth;
    result.baselineY = layout.baselineY;
    return result;
}

} // namespace mdcore
